// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/site.ts";

const manifest = {
  "apps": {
    "deco-sites/tmp/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/tmp",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
